### ISSUE TITLE
Change structure of endpoints

### ISSUE THREAD

**Issue by calejvaldez** [ojosproject/api#1]
https://github.com/ojosproject/api/blob/5256613023ed16f2d5a4f5e907f542c7150cb935/app.py#L17

By keeping the URL above, the endpoint will become `https://api.ojosproject.org/send_sms`. You should make the following changes:

- Have a trailing forward slash (end each URL with `/`)
- Replace underscores in `@app.route()` with a dash
- Ensure `/iris/` is in the beginning of the route (`/iris/send-sms/`)

That way, the link will look more organized as: `https://api.ojosproject.org/iris/send-sms/`

**Comment by jasonbm2** [comment]
endpoint changed to "/iris/send_sms/"
